### PR TITLE
Support erc-20 tokens + days instead of blocks

### LINKED ISSUE #3: Extend MyBit Will to any ERC20 token
## Introduction
To enhance the user experience of MyBit Will (will.mybit.io) We want to extend the functionality to any ERC20 token.

Current Behaviour: Only Ether is supported
Desired Behaviour: Any ERC20 Token is supported.

## Requirements:

1. Must be clear that any ERC20 token is supported
1. Could be a dropdown to choose which token and then input value. Or you can propose a better, more scalable way to do this. Although it must be clear what token users are referring to.
1. Another solution could be to have users manually add tokens such as in metamask, although that is not the best UX.

## To Submit:

1. Comment on task with a staging URL to get approval for design and placement.
1. Please submit a pull request with the final version once complete.

## Additional information
If you have any questions, please don't hesitate to comment on the task. For faster interaction, you can reach the team at our [Gitter](https://gitter.im/Mybit-Foundation/DDF) channel.

## Disclaimer
All work completed via the MyBit Decentralised Development Fund is property of the MyBit Foundation (CHE-177.186.963) and may be used, re-used, and/or distributed, re-distributed by the MyBit Foundation for financial gain. The contributor holds no warrant nor claims for any future payments resulting from monetisation schemes originating from the MyBit Foundation or any of its affiliates. Where law permits outside of open source regulations, the contributor is not permitted to distribute any work completed via the MyBit Decentralised Development Fund (DDF) for personal gain.

### LINKED ISSUE #194: Use days instead of blocks on MyBit Will
Introduction: To enhance the user experience of MyBit Will (will.mybit.io) We want to replace the current method of verifying life based on Block numbers with number of days.

Current Behaviour: Choose in how many blocks one must verify they are alive.

Desired Behaviour: Choose an amount in days and the block number to distribute is calculated on the back-end without the user knowing.
Requirements:

1. Implement a "number of days" feature instead of inputting blocks
1. Calculation of Block number for verification deadline should be done on the back-end.
1. Anywhere on dApp that mentions Block # should be changed to date (such as on transaction and redeem page if applicable).

To Submit:

1. Comment on task with a staging URL to get approval for design and placement.
1. Please submit a pull request with the final version once complete.

Disclaimer
All work completed via the MyBit Decentralised Development Fund is property of the MyBit Foundation (CHE-177.186.963) and may be used, re-used, and/or distributed, re-distributed by the MyBit Foundation for financial gain. The contributor holds no warrant nor claims for any future payments resulting from monetisation schemes originating from the MyBit Foundation or any of its affiliates. Where law permits outside of open source regulations, the contributor is not permitted to distribute any work completed via the MyBit Decentralised Development Fund (DDF) for personal gain.

### PR DESCRIPTION
**Pull request by StevenJNPearce**
Fixes: https://github.com/MyBitFoundation/MyBit-Will.tech/issues/3
Other PR for changes in the contract to support this functionality: https://github.com/MyBitFoundation/MyBit-Will.tech/pull/5

I've also included changes here to use days instead of blocks, fixes: https://github.com/MyBitFoundation/MyBit-Network.tech/issues/194
@PeterMPhillips had already made the changes in the contracts for this.

Testing URL: https://eager-williams-2d6193.netlify.com/
Choose Ropsten in metamask. Only MYB & ETH will work on ropsten; the other ERC-20 tokens only have mainnet addresses.

@csmartinsfct @mybit-bot @mybit-coordinator

### CODE REVIEW

**Comment by 0xjjpa** [comment]
👋 @StevenJNPearce ! Apologies for the delayed response in the work you've been doing. We had been a bit busy with some internal projects but we are back on track. We'll follow up on this one, thank you!

**Comment by 0xjjpa** [comment]
@StevenJNPearce feel free to follow-up our progress on https://public.3.basecamp.com/p/dtcmBWU41vC8cMYfXhGZvwj8 ☺️

**Comment by StevenJNPearce** [comment]
> 👋 @StevenJNPearce ! Apologies for the delayed response in the work you've been doing. We had been a bit busy with some internal projects but we are back on track. We'll follow up on this one, thank you!

Thanks for the update, looking forward to feedback/merging on the various issues.

**Review by 0xdewy — APPROVED** [review]
Look greats. Thanks @StevenJNPearce

**Pull request merged**
